In [19]:
import numpy as np
x = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])
print(x)

[[4 5 0]
 [1 9 3]
 [5 1 1]
 [3 3 3]
 [9 9 9]
 [4 7 1]]


In [21]:
m = np.mean(x, axis=0)
std = np.std(x, axis=0)
x_norm = ((x - m)/std)
print(x_norm)

[[-0.13736056 -0.2236068  -0.95481513]
 [-1.37360564  1.11803399  0.0561656 ]
 [ 0.27472113 -1.56524758 -0.61782155]
 [-0.54944226 -0.89442719  0.0561656 ]
 [ 1.9230479   1.11803399  2.07812704]
 [-0.13736056  0.4472136  -0.61782155]]


In [29]:
z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])
r = np.sum(z, axis=1)
print(r)
print (np.nonzero(r < 10))

[ 9 13  7  9 27 12]
(array([0, 2, 3], dtype=int64),)


In [32]:
a = np.eye(3)
b = np.eye(3)
print(a)
print(b)
ab = np.vstack((a,b))
print(ab)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
